# -*- coding: utf-8 -*-
"""project CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wjk4QT8GD7kbQ0Hsl0uaflQyjrkZXWeh
"""

from google.colab import drive
drive.mount('/content/my_drive')

import os
import cv2
import numpy as np

input_path = r"/content/my_drive/MyDrive/archive"
output_path = r"/content/my_drive/MyDrive/processed data "

os.makedirs(output_path, exist_ok=True)

def clean_name(name):
    base = name.split('.')[0]
    cleaned = "".join([c for c in base if c.isalnum()])
    return cleaned

def remove_duplicates(files):
    unique = []
    duplicates = []

    for f in files:
        cleaned = clean_name(f)
        if cleaned not in unique:
            unique.append(cleaned)
        else:
            duplicates.append(f)

    return duplicates

def apply_clahe_lab(img):
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    L, A, B = cv2.split(lab)
    A = (A * 0.9).astype("uint8")
    B = (B * 0.9).astype("uint8")
    clahe = cv2.createCLAHE(clipLimit=1.5, tileGridSize=(8, 8))
    L_eq = clahe.apply(L)
    lab_eq = cv2.merge((L_eq, A, B))
    result = cv2.cvtColor(lab_eq, cv2.COLOR_LAB2BGR)
    return result

def denoise(img):
    return cv2.fastNlMeansDenoisingColored(img, None, 10, 10, 7, 11)

def resize_image(img, size=(223, 223)):
    return cv2.resize(img, size)

def normalize(img):
    norm = img.astype("float32") / 255.0
    norm = (norm * 255).astype("uint8")
    return norm

total_deleted = 0

for root, dirs, files in os.walk(input_path):

    duplicates = remove_duplicates(files)
    if duplicates:
        print(f"Duplicates removed in folder '{root}': {len(duplicates)}")
        total_deleted += len(duplicates)
        for d in duplicates:
            files.remove(d)

    for filename in files:
        if filename.lower().endswith((".jpg", ".jpeg", ".png", ".bmp")):
            img_path = os.path.join(root, filename)
            img = cv2.imread(img_path)

            if img is None:
                print("Failed to read image:", img_path)
                continue

            relative_path = os.path.relpath(root, input_path)
            save_dir = os.path.join(output_path, relative_path)
            os.makedirs(save_dir, exist_ok=True)

            img = apply_clahe_lab(img)
            img = denoise(img)
            img = resize_image(img)
            img = normalize(img)

            save_path = os.path.join(save_dir, filename)
            cv2.imwrite(save_path, img)

print(f"\nProcessing completed successfully!")
print(f"Total duplicates deleted: {total_deleted}")

import os
import shutil
import random

# ----- إعداد المسارات -----
input_path = "/content/my_drive/MyDrive/processed data"  # مجلد الصور المعالجة
output_path = "/content/my_drive/MyDrive/processed_data_split"  # المجلد الجديد للتقسيم
train_ratio = 0.8
test_ratio = 0.2

# إنشاء مجلدات Train و Test
train_path = os.path.join(output_path, "Train")
test_path = os.path.join(output_path, "Test")
os.makedirs(train_path, exist_ok=True)
os.makedirs(test_path, exist_ok=True)

# ----- تقسيم الصور -----
for category in os.listdir(input_path):
    category_path = os.path.join(input_path, category)
    if not os.path.isdir(category_path):
        continue

    # إنشاء مجلدات الفئة داخل Train و Test
    os.makedirs(os.path.join(train_path, category), exist_ok=True)
    os.makedirs(os.path.join(test_path, category), exist_ok=True)

    images = [f for f in os.listdir(category_path) if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp"))]
    random.shuffle(images)

    split_index = int(len(images) * train_ratio)
    train_images = images[:split_index]
    test_images = images[split_index:]

    # نسخ الصور
    for img_name in train_images:
        src = os.path.join(category_path, img_name)
        dst = os.path.join(train_path, category, img_name)
        shutil.copy2(src, dst)

    for img_name in test_images:
        src = os.path.join(category_path, img_name)
        dst = os.path.join(test_path, category, img_name)
        shutil.copy2(src, dst)

    print(f"{category}: {len(train_images)} train, {len(test_images)} test")

print("\n✅ تم تقسيم البيانات إلى Train و Test بنجاح!")
print(f"Train folder: {train_path}")
print(f"Test folder: {test_path}")

import tensorflow as tf
from tensorflow.keras.applications import VGG16
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.models import Model
import matplotlib.pyplot as plt
import os


train_dir = "/content/my_drive/MyDrive/processed_data_split/Train"

img_size = (224,224)
batch_size = 32
epochs = 5
AUTOTUNE = tf.data.AUTOTUNE

train_ds = tf.keras.utils.image_dataset_from_directory(
   train_dir,
   image_size = img_size,
   batch_size = batch_size,
   label_mode = "categorical",
   shuffle = True
)


class_names = train_ds.class_names
num_classes = len(class_names)
print("Class names:", class_names)
print("Number of classes:", num_classes)

train_ds = train_ds.cache().prefetch(AUTOTUNE)

base_model = VGG16(weights="imagenet", include_top=False, input_shape=(img_size[0], img_size[1], 3))
base_model.trainable = False  # freeze pretrained layers (transfer learning)


x = Flatten()(base_model.output)
x = Dense(256, activation="relu")(x)
x = Dropout(0.5)(x)
output = Dense(num_classes, activation="softmax")(x)

model = Model(inputs=base_model.input, outputs=output)




model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()




history = model.fit(
    train_ds,
    epochs=epochs
)



save_path = "vgg16_fruit_transfer.h5"
model.save(save_path)
print(f"Model saved to: {os.path.abspath(save_path)}")

# -----------------------------
# 9. Plot training curves (accuracy & loss)
# -----------------------------
plt.figure(figsize=(12,5))

# Accuracy
plt.subplot(1,2,1)
plt.plot(history.history.get('accuracy', []), label='train_acc')
plt.title('Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss
plt.subplot(1,2,2)
plt.plot(history.history.get('loss', []), label='train_loss')
plt.title('Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()



import tensorflow as tf
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt

# -----------------------------
# 1) Load the trained model
# -----------------------------
model = tf.keras.models.load_model("/content/vgg16_fruit_transfer.h5")
print("The VGG16 model loaded successfully")

# -----------------------------
# 2) Load class names from Train folder
# -----------------------------
train_dir = "/content/my_drive/MyDrive/processed_data_split/Train"

temp = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=(224,224),
    batch_size=32,
    shuffle=False,
)

class_names = temp.class_names
print("Classes found:", class_names)

# -----------------------------
# 3) Test directory
# -----------------------------
test_dir = "/content/my_drive/MyDrive/processed_data_split/Test"

total_images = 0
correct_predictions = 0

# -----------------------------
# 4) Loop over each class folder
# -----------------------------
for class_folder in os.listdir(test_dir):

    class_path = os.path.join(test_dir, class_folder)

    if not os.path.isdir(class_path):
        continue

    print(f"\n--- Testing class: {class_folder} ---")

    for img_name in os.listdir(class_path):

        img_path = os.path.join(class_path, img_name)

        if not img_name.lower().endswith((".jpg", ".jpeg", ".png", ".bmp")):
            continue

        img = cv2.imread(img_path)
        if img is None:
            print("Failed to read:", img_path)
            continue

        # Preprocess image
        resized_img = cv2.resize(img, (224,224))
        resized_img = resized_img.astype("float32") / 255.0
        resized_img = np.expand_dims(resized_img, axis=0)

        # Prediction
        pred = model.predict(resized_img, verbose=0)
        class_id = np.argmax(pred)
        confidence = np.max(pred)
        predicted_class = class_names[class_id]

        total_images += 1
        if predicted_class == class_folder:
            correct_predictions += 1

        print(f"{img_name}  -->  Predicted: {predicted_class}  |  Confidence: {confidence:.4f}")

# -----------------------------
# 5) Final Accuracy on Test Set
# -----------------------------
accuracy = correct_predictions / total_images * 100
print("\n==============================")
print(f"Total Test Images: {total_images}")
print(f"Correct Predictions: {correct_predictions}")
print(f"Test Accuracy: {accuracy:.2f}%")
print("==============================")

# -----------------------------
# 6) Plot Accuracy (Bar Chart)
# -----------------------------
plt.figure(figsize=(6,5))
plt.bar(["Test Accuracy"], [accuracy])
plt.ylim(0, 100)
plt.ylabel("Accuracy (%)")
plt.title("Model Accuracy on Test Dataset")
plt.text(0, accuracy + 2, f"{accuracy:.2f}%", ha='center', fontsize=12)
plt.show()

